<?php

namespace app\controllers;

use app\models\ContactForm;
use app\models\Leadership;
use app\models\Page;
use yii\base\ErrorException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class AboutController extends Controller
{
    public $content;

    public function beforeAction($action)
    {
        if (!in_array($action->id, [
            'leadership-view',
        ])) {
            $page = Page::findOne(['route' => \Yii::$app->controller->route]);
            if (!$page)
                throw new NotFoundHttpException();

            $this->content = $page->content;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionHistoryDevelopment()
    {
        $this->view->title = 'История развития';
        return $this->render('//layouts/standard-page', ['content' => $this->content]);
    }
}