<?php

namespace app\controllers;

use app\models\Image;
use app\models\Leadership;
use app\models\News;
use app\models\Page;
use app\models\Product;
use yii\base\ErrorException;
use yii\web\Controller;
use yii\web\UploadedFile;

class AdminController extends Controller
{
    public $layout = 'admin/main';

    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest)
            $this->redirect(['site/login']);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionPages()
    {
        $pages = Page::find()
            ->orderBy(['id' => SORT_DESC])
            ->all();

        return $this->render('pages', compact('pages'));
    }

    public function actionPageEdit($id)
    {
        $page = Page::findOne($id);
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $page->load($request);

            if (!$page->save())
                throw new ErrorException();
        }

        $page = Page::findOne($id);

        return $this->render('page-edit', compact('page'));
    }

    public function actionPageCreate()
    {
        $page = new Page();
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();

            $page->load($request);
            if (!$page->save())
                throw new ErrorException();

            $this->redirect('pages');
        }

        return $this->render('page-create', compact('page'));
    }

    public function actionNews()
    {
        $news = News::getAllSortByIDesc();

        return $this->render('news', compact('news'));
    }

    public function actionNewsEdit($slug)
    {
        $news = News::findOne(['slug' => strip_tags($slug)]);
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $news->load($request);

            $image = UploadedFile::getInstance($news, 'image');
            if ($image)
                $news->main_image_id = Image::saveImage($image);

            if (!$news->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Новость успешно сохранена!');
            return $this->redirect(['admin/news']);
        }

        return $this->render('news-form', compact('news'));
    }

    public function actionNewsCreate()
    {
        $news = new News();
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $news->load($request);

            $image = UploadedFile::getInstance($news, 'image');
            if ($image)
                $news->main_image_id = Image::saveImage($image);

            if (!$news->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Новость успешно сохранена!');
            return $this->redirect(['admin/news']);
        }

        return $this->render('news-form', compact('news'));
    }

    public function actionProducts()
    {
        $products = Product::find()
            ->orderBy(['id' => SORT_DESC])
            ->all();

        return $this->render('products', compact('products'));
    }

    public function actionProductCreate()
    {
        $product = new Product();
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $product->load($request);

            $image = UploadedFile::getInstance($product, 'image');
            if ($image)
                $product->main_image_id = Image::saveImage($image);

            if (!$product->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Продукт успешно сохранен!');
            return $this->redirect(['admin/products']);
        }

        return $this->render('product-form', compact('product'));
    }

    public function actionProductEdit($slug)
    {
        $product = Product::findOne(['slug' => strip_tags($slug)]);
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $product->load($request);

            $image = UploadedFile::getInstance($product, 'image');
            if ($image)
                $product->main_image_id = Image::saveImage($image);

            if (!$product->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Продукт успешно сохранен!');
            return $this->redirect(['admin/products']);
        }

        return $this->render('product-form', compact('product'));
    }

    public function actionLeadership()
    {
        $leadership = Leadership::find()
            ->orderBy(['id' => SORT_DESC])
            ->all();

        return $this->render('leadership', compact('leadership'));
    }

    public function actionLeadershipCreate()
    {
        $leadership = new Leadership();
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $leadership->load($request);

            $image = UploadedFile::getInstance($leadership, 'image');
            if ($image)
                $leadership->main_image_id = Image::saveImage($image);

            if (!$leadership->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Руководитель успешно сохранен!');
            return $this->redirect(['admin/leadership']);
        }

        return $this->render('leadership-form', compact('leadership'));
    }

    public function actionLeadershipEdit($slug)
    {
        $leadership = Leadership::findOne(['slug' => strip_tags($slug)]);
        if (\Yii::$app->request->post())
        {
            $request = \Yii::$app->request->post();
            $leadership->load($request);

            $image = UploadedFile::getInstance($leadership, 'image');
            if ($image)
                $leadership->main_image_id = Image::saveImage($image);

            if (!$leadership->save())
                throw new ErrorException();

            \Yii::$app->session->setFlash('success', 'Руководитель успешно сохранен!');
            return $this->redirect(['admin/leadership']);
        }

        return $this->render('leadership-form', compact('leadership'));
    }

}