<?php

namespace app\models;

use yii\base\ErrorException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\web\ForbiddenHttpException;
use yii\web\UploadedFile;

/**
 * Class Document
 * @package app\models
 *
 * @property integer $id
 * @property string $path
 * @property integer $created_at
 * @property integer $updated_at
 */

class Document extends ActiveRecord
{
    public static function tableName()
    {
        return 'document';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public static function noDocument()
    {
        return \Yii::getAlias('@web/images/site/no-document.png');
    }

    public static function saveDocument(UploadedFile $file)
    {
        $documentDir = time();
        $uploadDir = \Yii::getAlias('@webroot/upload/images/' . $documentDir);
        if (!FileHelper::createDirectory($uploadDir))
            throw new ForbiddenHttpException();

        $path = \Yii::getAlias('@web/upload/images/' . $documentDir) . '/' . $file->name;
        if ($file->saveAs($uploadDir . '/' . $file->name)) {
            $document = new self();
            $document->path = $path;

            if (!$document->save())
                throw new ErrorException();

            return $document->id;
        }

        return null;
    }

    public function afterSave($insert, $changedAttributes)
    {
        var_dump($changedAttributes);die;
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['path'], 'string'],
            [['created_at', 'updated_at'], 'integer'],
        ];
    }
}