<?php


namespace app\models;

/**
 * Class Product
 * @package app\models
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $title
 * @property string $content
 */

class FeatureProduct extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'feature_product';
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['title', 'content'], 'string'],
            [['product_id', 'created_at', 'updated_at'], 'integer'],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}