<?php

namespace app\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * Class Pages
 * @package app\models
 *
 * @property integer $id;
 * @property string $route;
 * @property string $content;
 * @property integer $is_active;
 * @property integer $created_at
 * @property integer $updated_at
 */

class Page extends ActiveRecord
{
    public static function tableName()
    {
        return 'page';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['route'], 'required'],
            [['route', 'content'], 'string'],
            [['is_active', 'created_at', 'updated_at'], 'integer'],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}